compile_sass = true
generate_feed = true
base_url = "https://tensorush.github.io"
taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"

[slugify]
paths = "off"
anchors = "off"
taxonomies = "off"

[link_checker]
skip_prefixes = ["https://"]
skip_anchor_prefixes = ["https://"]
