title = "Computer Resource Types"
date = "2023-09-24"
weight = 2
summary = """
Classification of computer resources I've pulled out of thin air.
"""
content = """
| Resource Type | Interface Unit |    Example App     |
|:-------------:|:--------------:|:------------------:|
|      CPU      |     Thread     | Multimedia player  |
|     Disk      |      File      |  Antivirus daemon  |
|    Memory     |   Cache line   |     Video game     |
|    Network    |     Socket     | Application server |
"""

[taxonomies]
authors = ["tensorush"]
categories = ["blog"]
tags = ["swe"]
