title = "Cheer Stunting Guide"
date = "2023-10-03"
summary = """
Illustrated textbook of basic cheerleading stunts.
"""
content = """

## Massive props:

- [Hybrid Cheer](https://www.hybridcheer.com/pages/about-us)

- [Eliza Labelle](https://www.youtube.com/@elizalabelle)

- [Bonde Johnson](https://www.youtube.com/@bonde.johnson)

- [Daniel Buyeske](https://www.youtube.com/@danielbuyeske)

- [Gauge Stricklin](https://www.youtube.com/@Strictlycheer)

## Types of stunts:

- #pose - one-foot flyer poses
- #startup - ways to get into a stunt
- #dismount - ways to get down from a stunt
- #static - static ways to chain stunts together
- #dynamic - dynamic ways to chain stunts together
- #extra - extra ways to mix it up for most stunts
- #hands - ways for a flyer to kick into a handstand
- #spin - ways to spin into, during or out of most stunts
- #flip - ways to flip into, during or out of most stunts

## Advice to bases:

1) Don't drop your flyers.
2) Keep your free hand on your hip.
3) Make sure to switch to the non-dominant hand.

## Advice to flyers:

1) Stay light and cute.
2) Keep your chin, chest and toes up.
3) Keep your body straight and above the base.

# **Y'all be safe and have fun, happy stuntin'!**
"""

# Poses

[[pictures]]
pid = "hvl"
file = "hvl"
caption = "High-V #pose"
alt = "https://youtu.be/3ju2179PNC8?t=132"

[[pictures]]
pid = "scl"
file = "scl"
caption = "Scale #pose"
alt = ""

[[pictures]]
pid = "trh"
file = "trh"
caption = "Torch #pose"
alt = ""

[[pictures]]
pid = "sth"
file = "sth"
caption = "Stretch #pose"
alt = "https://youtu.be/kOSlKw79qdA?t=728"

[[pictures]]
pid = "scn"
file = "scn"
caption = "Scorpion #pose"
alt = ""

[[pictures]]
pid = "rbq"
file = "rbq"
caption = "Arabesque #pose"
alt = "https://youtu.be/kOSlKw79qdA?t=576"

# Jumps

[[pictures]]
pid = "pkj"
file = "pkj"
caption = "Pike #jump"
alt = ""

[[pictures]]
pid = "hkj"
file = "hkj"
caption = "Herkie #jump"
alt = ""

[[pictures]]
pid = "hdr"
file = "hdr"
caption = "Hurdler #jump"
alt = ""

[[pictures]]
pid = "tth"
file = "tth"
caption = "Toe-touch #jump"
alt = ""

[[pictures]]
pid = "dlh"
file = "dlh"
caption = "Double hook #jump"
alt = ""

[[pictures]]
pid = "sdg"
file = "sdg"
caption = "Spread eagle #jump"
alt = ""

# Tosses

[[pictures]]
pid = "tsl"
file = "tsl"
caption = "Toss lib #toss"
alt = ""

[[pictures]]
pid = "tsh"
file = "tsh"
caption = "Toss hands #toss"
alt = "https://youtu.be/1hzO2X9e_CE?t=61"

[[pictures]]
pid = "tst"
file = "tst"
caption = "Toss fists #toss"
alt = "https://youtu.be/7HU_bauP2lI?t=617"

[[pictures]]
pid = "tsp"
file = "tsp"
caption = "Toss platform #toss"
alt = ""

[[pictures]]
pid = "tsx"
file = "tsx"
caption = "Toss extension #toss"
alt = "https://youtu.be/9LaHx5fUn6s?t=716"

[[pictures]]
pid = "tsc"
file = "tsc"
caption = "Toss cupie #toss"
alt = ""

[[pictures]]
pid = "tsr"
file = "tsr"
caption = "Toss recliner #toss"
alt = "https://youtu.be/aybcpdbEbNw?t=582"

[[pictures]]
pid = "dpt"
file = "dpt"
caption = "Drop toss #toss"
alt = ""

[[pictures]]
pid = "spm"
file = "spm"
caption = "Superman #toss"
alt = "https://youtu.be/3pC9y3dZVrU?t=696"

# Dismounts

[[pictures]]
pid = "cdl"
file = "cdl"
caption = "Cradle #dismount"
alt = "https://youtu.be/kOSlKw79qdA?t=578"

[[pictures]]
pid = "ppf"
file = "ppf"
caption = "Pop off #dismount"
alt = "https://youtu.be/HMBSWEz2l24?t=672"

[[pictures]]
pid = "snf"
file = "snf"
caption = "Sign off #dismount"
alt = "https://youtu.be/LV3RCD7S-GE?t=201"

[[pictures]]
pid = "stt"
file = "stt"
caption = "Set out #dismount"
alt = "https://youtu.be/WBMVkXf3oBU?t=755"

# Extras

[[pictures]]
pid = "nrm"
file = "nrm"
caption = "One-arm #extra"
alt = "https://youtu.be/REmmtNLAF7Q?t=150"

[[pictures]]
pid = "nlg"
file = "nlg"
caption = "One-leg #extra"
alt = "https://youtu.be/Pp5O3fj7Pbc?t=763"

[[pictures]]
pid = "nlk"
file = "nlk"
caption = "No-look #extra"
alt = "https://youtu.be/ApTsZwIDYLU?t=421"

[[pictures]]
pid = "ldh"
file = "ldh"
caption = "Lend-a-hand #extra"
alt = "https://youtu.be/LV3RCD7S-GE?t=873"

[[pictures]]
pid = "ddt"
file = "ddt"
caption = "Dead toss #extra"
alt = "https://youtu.be/ApTsZwIDYLU?t=473"

[[pictures]]
pid = "msw"
file = "msw"
caption = "Arm switch #extra"
alt = ""

[[pictures]]
pid = "ptl"
file = "ptl"
caption = "Opposite leg #extra"
alt = ""

[[pictures]]
pid = "pts"
file = "pts"
caption = "Opposite spin #extra"
alt = ""

[[pictures]]
pid = "mdt"
file = "mdt"
caption = "Immediate / Pull through #extra"
alt = "https://youtu.be/HMBSWEz2l24?t=316"

# Statics

[[pictures]]
pid = "prp"
file = "prp"
caption = "Prep #static"
alt = ""

[[pictures]]
pid = "vsr"
file = "vsr"
caption = "Visor #static"
alt = ""

[[pictures]]
pid = "dlv"
file = "dlv"
caption = "Double Visor #static"
alt = "https://youtu.be/7HU_bauP2lI?t=601"

[[pictures]]
pid = "gvt"
file = "gvt"
caption = "Gravity #static"
alt = ""

[[pictures]]
pid = "stg"
file = "stg"
caption = "Split gravity #static"
alt = "https://youtu.be/3ju2179PNC8?t=272"

[[pictures]]
pid = "sst"
file = "sst"
caption = "Shoulder sit #static"
alt = "https://youtu.be/ApTsZwIDYLU?t=119"

[[pictures]]
pid = "ssd"
file = "ssd"
caption = "Shoulder stand #static"
alt = ""

[[pictures]]
pid = "gsd"
file = "gsd"
caption = "Genie stand #static"
alt = ""

# Dynamics

[[pictures]]
pid = "tct"
file = "tct"
caption = "Tic-toc #dynamic"
alt = "https://youtu.be/ey00mPkhMCs?t=234"

[[pictures]]
pid = "ppv"
file = "ppv"
caption = "Pop over #dynamic"
alt = "https://youtu.be/UnSqDsi_6lE?t=148"

[[pictures]]
pid = "flv"
file = "flv"
caption = "Full over #dynamic"
alt = "https://youtu.be/7HU_bauP2lI?t=433"

[[pictures]]
pid = "pps"
file = "pps"
caption = "Power press #dynamic"
alt = ""

[[pictures]]
pid = "ppt"
file = "ppt"
caption = "Pop through #dynamic"
alt = ""

[[pictures]]
pid = "rpt"
file = "rpt"
caption = "Reverse pop through #dynamic"
alt = "https://youtu.be/7HU_bauP2lI?t=688"

# Start-ups

[[pictures]]
pid = "wkn"
file = "wkn"
caption = "Walk-in #startup"
alt = "https://youtu.be/Pp5O3fj7Pbc?t=644"

[[pictures]]
pid = "blp"
file = "blp"
caption = "Ball-up #startup"
alt = "https://youtu.be/KsHd_mN0a84?t=73"

[[pictures]]
pid = "flp"
file = "flp"
caption = "Full-up #startup"
alt = "https://youtu.be/HMBSWEz2l24?t=298"

[[pictures]]
pid = "dlp"
file = "dlp"
caption = "Double-up #startup"
alt = "https://youtu.be/vUINVgnZBAQ?t=424"

[[pictures]]
pid = "stp"
file = "stp"
caption = "Split-up #startup"
alt = "https://youtu.be/HMBSWEz2l24?t=664"

[[pictures]]
pid = "swp"
file = "swp"
caption = "Swing-up #startup"
alt = "https://youtu.be/_qJulETphrI?t=174"

[[pictures]]
pid = "bmr"
file = "bmr"
caption = "Boomerang #startup"
alt = "https://youtu.be/Vsq-m_Rd7Zk?t=767"

[[pictures]]
pid = "ssm"
file = "ssm"
caption = "Side-semi #startup"
alt = ""

[[pictures]]
pid = "cnb"
file = "cnb"
caption = "Cannonball #startup"
alt = "https://youtu.be/ey00mPkhMCs?t=679"

[[pictures]]
pid = "bhp"
file = "bhp"
caption = "Back-handspring-up #startup"
alt = "https://youtu.be/LV3RCD7S-GE?t=455"

[[pictures]]
pid = "fhp"
file = "fhp"
caption = "Front-handspring-up #startup"
alt = "https://youtu.be/ebOIvS87YpM?t=621"

# Spins

[[pictures]]
pid = "ftw"
file = "ftw"
caption = "Full twist #spin"
alt = "https://youtu.be/DfFdPsbxVPQ?t=609"

[[pictures]]
pid = "fld"
file = "fld"
caption = "Full-around #spin"
alt = "https://youtu.be/LV3RCD7S-GE?t=314"

[[pictures]]
pid = "nnh"
file = "nnh"
caption = "One-and-a-half-around #spin"
alt = "https://youtu.be/u1x7tgvlO3M?t=518"

[[pictures]]
pid = "rtw"
file = "rtw"
caption = "Around-the-world #spin"
alt = "https://youtu.be/hw7tZkE-dHk?t=354"

# Hands

[[pictures]]
pid = "hsk"
file = "hsk"
caption = "Hand-ski #hands"
alt = "https://youtu.be/_qJulETphrI?t=729"

[[pictures]]
pid = "dmd"
file = "dmd"
caption = "Diamidov #hands"
alt = "https://youtu.be/7HU_bauP2lI?t=302"

[[pictures]]
pid = "dtd"
file = "dtd"
caption = "Hand-to-hand #hands"
alt = "https://youtu.be/LV3RCD7S-GE?t=172"

[[pictures]]
pid = "ddv"
file = "ddv"
caption = "Dolphin dive #hands"
alt = "https://youtu.be/UnSqDsi_6lE?t=405"

# Flips

[[pictures]]
pid = "rwd"
file = "rwd"
caption = "Rewind #flip"
alt = "https://youtu.be/LV3RCD7S-GE?t=375"

[[pictures]]
pid = "stn"
file = "stn"
caption = "Shotgun #flip"
alt = "https://youtu.be/CDZ0CePSQ40?t=261"

[[pictures]]
pid = "oto"
file = "oto"
caption = "One-to-one #flip"
alt = "https://youtu.be/SwaejeJ8kPk?t=477"

[taxonomies]
authors = ["tensorush"]
categories = ["cheer"]
tags = ["gallery"]
