title = "Cheer Stunting Gallery"
date = "2023-10-03"
summary = """
Snapshot collection of basic cheerleading stunts.
"""
content = """

## Massive props:

* [Hybrid Cheer](https://www.hybridcheer.com/pages/about-us)
* [Eliza LaBelle](https://www.youtube.com/@elizalabelle)
* [Bonde Johnson](https://www.youtube.com/@bonde.johnson)
* [Daniel Buyeske](https://www.youtube.com/@danielbuyeske)
* [Gauge Stricklin](https://www.youtube.com/@Strictlycheer)

## Types of stunts:

* #move — moving a flyer
* #toss — tossing a flyer
* #hold — holding a flyer
* #spin — spinning a flyer
* #flip — flipping a flyer
* #pose — flyer striking a pose
* #jump — flyer jumping upwards
* #hand — flyer doing a handstand
* #rise — flyer rising up into a stunt
* #drop — flyer dropping down from a stunt
* #more — making it more difficult to stunt

## Advice to bases:

1) Always have a spotter.
2) Keep your free hand on your hip.
3) Make sure to switch to the non-dominant hand.

## Advice to flyers:

1) Stay light and cute.
2) Keep your chin, chest and toes up.
3) Keep your body straight and above the base.

# **Y'all be safe and have fun, happy stuntin'!**
"""

# Move

[[pictures]]
pid = "tct"
file = "tct"
caption = "Tic-toc #move"
alt = "https://youtu.be/ey00mPkhMCs?t=234"

[[pictures]]
pid = "ppv"
file = "ppv"
caption = "Pop over #move"
alt = "https://youtu.be/UnSqDsi_6lE?t=148"

[[pictures]]
pid = "flv"
file = "flv"
caption = "Full over #move"
alt = "https://youtu.be/7HU_bauP2lI?t=433"

[[pictures]]
pid = "pps"
file = "pps"
caption = "Power press #move"
alt = "https://youtu.be/0TN-f7vbnTQ?t=270"

[[pictures]]
pid = "ppt"
file = "ppt"
caption = "Pop through #move"
alt = "https://youtu.be/REmmtNLAF7Q?t=369"

[[pictures]]
pid = "rpt"
file = "rpt"
caption = "Reverse pop through #move"
alt = "https://youtu.be/7HU_bauP2lI?t=688"

# Toss

[[pictures]]
pid = "tsh"
file = "tsh"
caption = "Toss hands #toss"
alt = "https://youtu.be/1hzO2X9e_CE?t=61"

[[pictures]]
pid = "tst"
file = "tst"
caption = "Toss fists #toss"
alt = "https://youtu.be/7HU_bauP2lI?t=617"

[[pictures]]
pid = "tsp"
file = "tsp"
caption = "Toss platform #toss"
alt = "https://youtu.be/FZ4A0nTEtkc?t=107"

[[pictures]]
pid = "tsx"
file = "tsx"
caption = "Toss extension #toss"
alt = "https://youtu.be/9LaHx5fUn6s?t=716"

[[pictures]]
pid = "tsc"
file = "tsc"
caption = "Toss cupie #toss"
alt = "https://youtu.be/0TN-f7vbnTQ?t=579"

[[pictures]]
pid = "tsr"
file = "tsr"
caption = "Toss recliner #toss"
alt = "https://youtu.be/aybcpdbEbNw?t=582"

[[pictures]]
pid = "dpt"
file = "dpt"
caption = "Drop toss #toss"
alt = "https://youtu.be/qjbRUuxKr3Q?t=796"

[[pictures]]
pid = "spm"
file = "spm"
caption = "Superman #toss"
alt = "https://youtu.be/3pC9y3dZVrU?t=716"

# Hold

[[pictures]]
pid = "prp"
file = "prp"
caption = "Prep #hold"
alt = "https://youtu.be/FZ4A0nTEtkc?t=69"

[[pictures]]
pid = "vsr"
file = "vsr"
caption = "Visor #hold"
alt = "https://youtu.be/RLbde7dYHkI?t=235"

[[pictures]]
pid = "dlv"
file = "dlv"
caption = "Double Visor #hold"
alt = "https://youtu.be/7HU_bauP2lI?t=601"

[[pictures]]
pid = "gvt"
file = "gvt"
caption = "Gravity #hold"
alt = "https://youtube.com/shorts/EHGxbOI7mZQ"

[[pictures]]
pid = "stg"
file = "stg"
caption = "Split gravity #hold"
alt = "https://youtu.be/3ju2179PNC8?t=272"

[[pictures]]
pid = "sst"
file = "sst"
caption = "Shoulder sit #hold"
alt = "https://youtu.be/ApTsZwIDYLU?t=119"

[[pictures]]
pid = "ssd"
file = "ssd"
caption = "Shoulder stand #hold"
alt = "https://youtu.be/SonOnjYRtHU?t=281"

[[pictures]]
pid = "gsd"
file = "gsd"
caption = "Genie stand #hold"
alt = "https://youtu.be/RLbde7dYHkI?t=167"

# Spin

[[pictures]]
pid = "ftw"
file = "ftw"
caption = "Full twist #spin"
alt = "https://youtu.be/DfFdPsbxVPQ?t=609"

[[pictures]]
pid = "fld"
file = "fld"
caption = "Full-around #spin"
alt = "https://youtu.be/LV3RCD7S-GE?t=314"

[[pictures]]
pid = "nnh"
file = "nnh"
caption = "One-and-a-half-around #spin"
alt = "https://youtu.be/u1x7tgvlO3M?t=518"

[[pictures]]
pid = "rtw"
file = "rtw"
caption = "Around-the-world #spin"
alt = "https://youtu.be/hw7tZkE-dHk?t=354"

# Flip

[[pictures]]
pid = "rwd"
file = "rwd"
caption = "Rewind #flip"
alt = "https://youtu.be/LV3RCD7S-GE?t=375"

[[pictures]]
pid = "stn"
file = "stn"
caption = "Shotgun #flip"
alt = "https://youtu.be/CDZ0CePSQ40?t=261"

[[pictures]]
pid = "ntn"
file = "ntn"
caption = "One-to-one #flip"
alt = "https://youtu.be/SwaejeJ8kPk?t=477"

# Pose

[[pictures]]
pid = "hvl"
file = "hvl"
caption = "High-V #pose"
alt = "https://youtu.be/3ju2179PNC8?t=132"

[[pictures]]
pid = "scl"
file = "scl"
caption = "Scale #pose"
alt = ""

[[pictures]]
pid = "trh"
file = "trh"
caption = "Torch #pose"
alt = ""

[[pictures]]
pid = "sth"
file = "sth"
caption = "Stretch #pose"
alt = "https://youtu.be/kOSlKw79qdA?t=728"

[[pictures]]
pid = "scn"
file = "scn"
caption = "Scorpion #pose"
alt = ""

[[pictures]]
pid = "rbq"
file = "rbq"
caption = "Arabesque #pose"
alt = "https://youtu.be/kOSlKw79qdA?t=576"

# Jump

[[pictures]]
pid = "pkj"
file = "pkj"
caption = "Pike #jump"
alt = ""

[[pictures]]
pid = "hkj"
file = "hkj"
caption = "Herkie #jump"
alt = ""

[[pictures]]
pid = "hdr"
file = "hdr"
caption = "Hurdler #jump"
alt = ""

[[pictures]]
pid = "tth"
file = "tth"
caption = "Toe-touch #jump"
alt = ""

[[pictures]]
pid = "dlh"
file = "dlh"
caption = "Double hook #jump"
alt = ""

[[pictures]]
pid = "sdg"
file = "sdg"
caption = "Spread eagle #jump"
alt = ""

# Hand

[[pictures]]
pid = "hsk"
file = "hsk"
caption = "Hand-ski #hand"
alt = "https://youtu.be/_qJulETphrI?t=729"

[[pictures]]
pid = "dmd"
file = "dmd"
caption = "Diamidov #hand"
alt = "https://youtu.be/7HU_bauP2lI?t=302"

[[pictures]]
pid = "dtd"
file = "dtd"
caption = "Hand-to-hand #hand"
alt = "https://youtu.be/LV3RCD7S-GE?t=172"

[[pictures]]
pid = "ddv"
file = "ddv"
caption = "Dolphin dive #hand"
alt = "https://youtu.be/UnSqDsi_6lE?t=405"

# Rise

[[pictures]]
pid = "wkn"
file = "wkn"
caption = "Walk-in #rise"
alt = "https://youtu.be/Pp5O3fj7Pbc?t=644"

[[pictures]]
pid = "blp"
file = "blp"
caption = "Ball-up #rise"
alt = "https://youtu.be/KsHd_mN0a84?t=73"

[[pictures]]
pid = "flp"
file = "flp"
caption = "Full-up #rise"
alt = "https://youtu.be/FZ4A0nTEtkc?t=187"

[[pictures]]
pid = "dlp"
file = "dlp"
caption = "Double-up #rise"
alt = "https://youtu.be/vUINVgnZBAQ?t=424"

[[pictures]]
pid = "stp"
file = "stp"
caption = "Split-up #rise"
alt = "https://youtu.be/HMBSWEz2l24?t=664"

[[pictures]]
pid = "swp"
file = "swp"
caption = "Swing-up #rise"
alt = "https://youtu.be/_qJulETphrI?t=174"

[[pictures]]
pid = "bmr"
file = "bmr"
caption = "Boomerang #rise"
alt = "https://youtu.be/Vsq-m_Rd7Zk?t=767"

[[pictures]]
pid = "ssm"
file = "ssm"
caption = "Side-semi #rise"
alt = ""

[[pictures]]
pid = "cnb"
file = "cnb"
caption = "Cannonball #rise"
alt = "https://youtu.be/ey00mPkhMCs?t=679"

[[pictures]]
pid = "bhp"
file = "bhp"
caption = "Back-handspring-up #rise"
alt = "https://youtu.be/LV3RCD7S-GE?t=455"

[[pictures]]
pid = "fhp"
file = "fhp"
caption = "Front-handspring-up #rise"
alt = "https://youtu.be/ebOIvS87YpM?t=621"

# Drop

[[pictures]]
pid = "cdl"
file = "cdl"
caption = "Cradle #drop"
alt = "https://youtu.be/kOSlKw79qdA?t=578"

[[pictures]]
pid = "ppf"
file = "ppf"
caption = "Pop off #drop"
alt = "https://youtu.be/HMBSWEz2l24?t=672"

[[pictures]]
pid = "snf"
file = "snf"
caption = "Sign off #drop"
alt = "https://youtu.be/LV3RCD7S-GE?t=201"

# More

[[pictures]]
pid = "nrm"
file = "nrm"
caption = "One-arm #more"
alt = "https://youtu.be/REmmtNLAF7Q?t=150"

[[pictures]]
pid = "nlg"
file = "nlg"
caption = "One-leg #more"
alt = "https://youtu.be/Pp5O3fj7Pbc?t=763"

[[pictures]]
pid = "nlk"
file = "nlk"
caption = "No-look #more"
alt = "https://youtu.be/ApTsZwIDYLU?t=421"

[[pictures]]
pid = "ldh"
file = "ldh"
caption = "Lend-a-hand #more"
alt = "https://youtu.be/LV3RCD7S-GE?t=873"

[[pictures]]
pid = "ddt"
file = "ddt"
caption = "Dead toss #more"
alt = "https://youtu.be/ApTsZwIDYLU?t=473"

# [[pictures]]
# pid = "msw"
# file = "msw"
# caption = "Arm switch #more"
# alt = ""

# [[pictures]]
# pid = "ptl"
# file = "ptl"
# caption = "Opposite leg #more"
# alt = ""

# [[pictures]]
# pid = "pts"
# file = "pts"
# caption = "Opposite spin #more"
# alt = ""

[[pictures]]
pid = "mdt"
file = "mdt"
caption = "Immediate lib / Pull through #more"
alt = "https://youtu.be/HMBSWEz2l24?t=316"

[taxonomies]
authors = ["tensorush"]
categories = ["cheer"]
tags = ["gallery"]
