title = "Software Product Types"
date = "2023-09-23"
summary = """
Classification of software products I've pulled out of thin air.
"""
content = """
> Abbreviations:
>
> OTP - One-time payment, Don - Donation, Sub - Subscription,
>
> OTD - One-time download, Sync - Client-server synchronisation.

|   Product Type   |       Purpose Category       | Business Model  | Distribution Model |
|:----------------:|:----------------------------:|:---------------:|:------------------:|
|     Dev tool     |    Utility & Productivity    |    Don / OTP    |        OTD         |
|     User app     | Communication & Productivity | Don / OTP / Sub |        OTD         |
|    Video game    |     Art & Entertainment      |       OTP       |     OTD / Sync     |
| Content platform |   Communication & Creation   |       Sub       |        Sync        |
"""

[taxonomies]
authors = ["tensorush"]
categories = ["blog"]
tags = ["swe"]
