name: Continuos Delivery

on:
  push:
    branches: [main]
    paths: ["**.toml", "**.html", "**.css"]

  pull_request:
    branches: [main]
    paths: ["**.toml", "**.html", "**.css"]

  workflow_dispatch:

permissions:
  pages: write
  contents: read
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install blades with Cargo
        uses: baptiste0928/cargo-install@v2
        with:
          crate: blades
          git: https://github.com/grego/blades

      - name: Build site
        run: blades all

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public/

  deploy:
    needs: build

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy artifact to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
